"""create initial schema

Revision ID: 1fdcb561a39c
Revises: 
Create Date: 2025-06-09 18:30:00.828698

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '1fdcb561a39c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
